# Generated by Django 6.1 on 2026-08-28 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('screenings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialist_name', models.CharField(default='Dr. Arvind Swaminathan (Vitreoretinal Surgeon)', max_length=150)),
                ('hospital_name', models.CharField(db_index=True, default='Visakha Government Regional Eye Hospital', max_length=200)),
                ('facility_type', models.CharField(choices=[('TERTIARY_APEX', 'Tertiary Apex Center'), ('DISTRICT_HOSPITAL', 'District Eye Hospital'), ('MOBILE_UNIT', 'Mobile Tele-Ophthalmology Unit')], default='TERTIARY_APEX', max_length=40)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine (Standard Surveillance)'), ('PRIORITY', 'Priority (Within 30 Days)'), ('URGENT', 'Urgent (Within 7-14 Days)'), ('EMERGENCY', 'Emergency (Within 48 Hours)')], db_index=True, default='URGENT', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Referral Created'), ('REFERRED', 'Dispatched to Destination Hospital'), ('PATIENT_NOTIFIED', 'Patient Contacted & Informed'), ('APPOINTMENT_PENDING', 'Appointment Slot Requested'), ('APPOINTMENT_BOOKED', 'Appointment Confirmed'), ('SPECIALIST_REVIEW', 'Specialist Examination in Progress'), ('COMPLETED', 'Intervention & Care Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REFERRED', max_length=30)),
                ('target_date', models.DateField(db_index=True)),
                ('primary_diagnosis', models.CharField(default='Moderate NPDR with Rapid Progression & Early DME Threat', max_length=255)),
                ('transport_assistance_required', models.BooleanField(default=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_referrals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
                ('screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='screenings.screeningsession')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='referrals.referral')),
            ],
            options={
                'verbose_name': 'Referral Event',
                'verbose_name_plural': 'Referral Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
