# Generated by Django 6.1 on 2026-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='target_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
