# Generated by Django 6.1 on 2026-08-28 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patients_pa_organiz_fb112c_idx_and_more'),
        ('referrals', '0002_alter_referral_target_date'),
        ('screenings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['patient', 'status'], name='referrals_r_patient_fc132b_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['hospital_name', 'status'], name='referrals_r_hospita_44f1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['target_date', 'status'], name='referrals_r_target__3b5153_idx'),
        ),
    ]
