# Generated by Django 6.1 on 2026-08-28 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('HIGH_RISK', 'High Risk Screening Detected'), ('PROGRESSION_ALERT', 'Possible Disease Progression Alert'), ('FOLLOWUP_DUE', 'Patient Follow-up Due'), ('FOLLOWUP_OVERDUE', 'Follow-up Overdue / Lost to Follow-up'), ('REFERRAL_CREATED', 'Specialist Referral Created'), ('REFERRAL_UPDATED', 'Referral Stage Updated'), ('SYNC_REQUIRED', 'Offline Device Sync Pending'), ('SYSTEM', 'System Alert')], db_index=True, default='SYSTEM', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
