# Generated by Django 6.1 on 2026-08-28 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('URGENT', 'Urgent / Immediate Specialist Dispatch'), ('UNKNOWN', 'Unknown')], db_index=True, default='LOW', max_length=20)),
                ('risk_score', models.PositiveIntegerField(default=25, help_text='Calculated composite risk score 0 - 100')),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='List of clinical risk factors identified')),
                ('recommendation', models.JSONField(blank=True, default=dict, help_text='Structured action recommendations')),
                ('is_prototype_score', models.BooleanField(default=True, help_text='Clearly designates the risk score as an AI-assisted screening estimate.')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='patients.patient')),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='screenings.screeningsession')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
