# Generated by Django 6.1 on 2026-08-28 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('referrals', '0001_initial'),
        ('screenings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(db_index=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming Follow-up'), ('DUE', 'Due Today / Active Recall'), ('OVERDUE', 'Overdue - High Risk of Drop-out'), ('COMPLETED', 'Follow-up Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='UPCOMING', max_length=20)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine Recall (6-12 Months)'), ('URGENT', 'Urgent Recall (14-30 Days)')], db_index=True, default='ROUTINE', max_length=20)),
                ('recall_channel', models.CharField(choices=[('SMS', 'Automated Multilingual SMS'), ('CALL', 'ASHA Telephonic Call'), ('ASHA_VISIT', 'Physical ASHA Home Visit')], default='SMS', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='patients.patient')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='referrals.referral')),
                ('screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='screenings.screeningsession')),
            ],
            options={
                'verbose_name': 'Follow-Up',
                'verbose_name_plural': 'Follow-Ups',
                'ordering': ['due_date'],
            },
        ),
    ]
