# Generated by Django 6.1 on 2026-08-28 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
        ('patients', '0001_initial'),
        ('referrals', '0002_alter_referral_target_date'),
        ('screenings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['due_date', 'status'], name='followups_f_due_dat_464d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['patient', 'status'], name='followups_f_patient_58745f_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['priority', 'status'], name='followups_f_priorit_a794ce_idx'),
        ),
    ]
