# Generated by Django 6.1 on 2026-08-28 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_code', models.CharField(db_index=True, help_text='Human-readable patient ID e.g. RG-1042', max_length=50, unique=True)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Patient age in years', null=True)),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], default='FEMALE', max_length=20)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ta', 'Tamil')], default='te', max_length=10)),
                ('village', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('district', models.CharField(db_index=True, default='Visakhapatnam', max_length=100)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('diabetes_type', models.CharField(choices=[('TYPE_1', 'Type 1 Diabetes'), ('TYPE_2', 'Type 2 Diabetes'), ('GESTATIONAL', 'Gestational Diabetes'), ('PRE_DIABETIC', 'Pre-Diabetic'), ('UNKNOWN', 'Unknown / Unclassified')], default='TYPE_2', max_length=30)),
                ('diabetes_duration_years', models.PositiveIntegerField(default=5)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=1, help_text='Latest Glycated Hemoglobin %', max_digits=4, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('current_risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('URGENT', 'Urgent / Critical'), ('UNKNOWN', 'Unknown')], db_index=True, default='LOW', max_length=20)),
                ('current_severity', models.CharField(choices=[('NO_DR', 'No Apparent Diabetic Retinopathy'), ('MILD_DR', 'Mild Non-Proliferative DR'), ('MODERATE_DR', 'Moderate Non-Proliferative DR'), ('SEVERE_DR', 'Severe Non-Proliferative DR'), ('PROLIFERATIVE_DR', 'Proliferative Diabetic Retinopathy'), ('PROGRESSION', 'Possible Longitudinal Progression'), ('UNDETERMINED', 'Undetermined')], db_index=True, default='NO_DR', max_length=30)),
                ('has_progression_alert', models.BooleanField(db_index=True, default=False)),
                ('last_screening_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('SCREENING_AND_AI', 'Retinal Photography & AI-Assisted Screening'), ('DATA_SHARING_SPECIALIST', 'Clinical Data Sharing with Specialist Ophthalmologists'), ('RESEARCH_ANONYMIZED', 'Anonymized Epidemiological Research'), ('TELEMEDICINE', 'Tele-Ophthalmology Remote Consultation')], default='SCREENING_AND_AI', max_length=50)),
                ('granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Consent',
                'verbose_name_plural': 'Patient Consents',
                'unique_together': {('patient', 'consent_type')},
            },
        ),
    ]
