# Generated by Django 6.1 on 2026-08-28 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'current_risk_level'], name='patients_pa_organiz_fb112c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'current_severity'], name='patients_pa_organiz_41f36a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'has_progression_alert'], name='patients_pa_organiz_e70560_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['organization', 'last_screening_date'], name='patients_pa_organiz_ec77ec_idx'),
        ),
    ]
