# Generated by Django 6.0.3 on 2026-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patients_pa_organiz_fb112c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='avatar',
            field=models.TextField(blank=True, help_text='Patient profile photo base64 or URL', null=True),
        ),
    ]
