# Generated by Django 6.1 on 2026-08-28 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mock', help_text='AI provider backend name: mock, local, external_api', max_length=50)),
                ('model_name', models.CharField(default='RetinaGuard-DeepVision-Ensemble', max_length=150)),
                ('model_version', models.CharField(default='v2.4', max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued for Processing'), ('PROCESSING', 'Inference Running'), ('COMPLETED', 'Inference Completed'), ('FAILED', 'Inference Failed')], db_index=True, default='COMPLETED', max_length=20)),
                ('predicted_stage', models.CharField(choices=[('NO_DR', 'No Apparent Diabetic Retinopathy'), ('MILD', 'Mild Non-Proliferative DR'), ('MODERATE', 'Moderate Non-Proliferative DR'), ('SEVERE', 'Severe Non-Proliferative DR'), ('PROLIFERATIVE', 'Proliferative Diabetic Retinopathy'), ('UNDETERMINED', 'Undetermined / Inconclusive')], db_index=True, default='NO_DR', max_length=30)),
                ('confidence', models.DecimalField(decimal_places=4, default=0.942, help_text='Prediction confidence 0.0000 - 1.0000', max_digits=5)),
                ('processing_time_ms', models.PositiveIntegerField(default=180, help_text='Inference duration in milliseconds')),
                ('raw_scores', models.JSONField(blank=True, default=dict, help_text='Per-class probability distribution dictionary')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_simulation', models.BooleanField(default=False, help_text='Flagged true if run via mock demo provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retinal_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='screenings.retinalimage')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='screenings.screeningsession')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExplainabilityResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('GRAD_CAM', 'Gradient-weighted Class Activation Mapping (Grad-CAM)'), ('GRAD_CAM_PLUS_PLUS', 'Grad-CAM++ (High resolution multi-scale)'), ('INTEGRATED_GRADIENTS', 'Axiomatic Integrated Gradients'), ('OCCLUSION', 'Perturbation Occlusion Sensitivity'), ('OTHER', 'Other Attribution Architecture')], default='GRAD_CAM', max_length=40)),
                ('heatmap_path', models.CharField(blank=True, help_text='Relative media path to standalone heatmap image', max_length=255, null=True)),
                ('overlay_path', models.CharField(blank=True, help_text='Relative media path to blended fundus overlay', max_length=255, null=True)),
                ('regions', models.JSONField(blank=True, default=list, help_text='List of top contributing anatomical regions with coordinates')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explainability', to='retinal_analysis.aianalysis')),
            ],
            options={
                'verbose_name': 'Explainability Result',
                'verbose_name_plural': 'Explainability Results',
            },
        ),
        migrations.CreateModel(
            name='ImageQualityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_quality', models.CharField(choices=[('GOOD', 'Good Quality / Diagnostic Resolution'), ('ACCEPTABLE', 'Acceptable Quality'), ('POOR', 'Poor Quality / Motion Blur Detected')], db_index=True, default='GOOD', max_length=20)),
                ('sharpness', models.PositiveIntegerField(default=90, help_text='Sharpness score 0-100')),
                ('brightness', models.PositiveIntegerField(default=90, help_text='Brightness score 0-100')),
                ('contrast', models.PositiveIntegerField(default=90, help_text='Contrast score 0-100')),
                ('retinal_visibility', models.PositiveIntegerField(default=95, help_text='Retinal visibility percentage 0-100')),
                ('field_of_view', models.PositiveIntegerField(default=45, help_text='Field of View in degrees e.g. 45')),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of detected optical defects e.g. ["MOTION_BLUR"]')),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Proceed to AI Inference'), ('RETAKE', 'Retake Retinal Image Before Inference')], default='ACCEPT', max_length=20)),
                ('algorithm_version', models.CharField(default='OpenCV-v2.4', max_length=50)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('retinal_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assessment', to='screenings.retinalimage')),
            ],
            options={
                'verbose_name': 'Image Quality Assessment',
                'verbose_name_plural': 'Image Quality Assessments',
            },
        ),
        migrations.CreateModel(
            name='RetinalFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_type', models.CharField(choices=[('MICROANEURYSM', 'Microaneurysm (Focal capillary dilation)'), ('HEMORRHAGE', 'Flame / Blot Retinal Hemorrhage'), ('EXUDATE', 'Hard Lipid Exudate Cluster'), ('COTTON_WOOL_SPOT', 'Cotton Wool Spot (Nerve fiber infarction)'), ('NEOVASCULARIZATION', 'Neovascularization (NVD / NVE Abnormal Vessel Tuft)'), ('OTHER', 'Other Microvascular Alteration')], db_index=True, default='MICROANEURYSM', max_length=30)),
                ('confidence', models.DecimalField(decimal_places=4, default=0.91, max_digits=5)),
                ('severity', models.CharField(choices=[('TRACE', 'Trace / Isolated'), ('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe / Confluent')], default='MILD', max_length=20)),
                ('x', models.FloatField(default=0.0, help_text='Normalized horizontal origin coordinate 0.0 - 1.0')),
                ('y', models.FloatField(default=0.0, help_text='Normalized vertical origin coordinate 0.0 - 1.0')),
                ('width', models.FloatField(default=0.05, help_text='Normalized width 0.0 - 1.0')),
                ('height', models.FloatField(default=0.05, help_text='Normalized height 0.0 - 1.0')),
                ('area', models.FloatField(default=0.0, help_text='Pixel area measurement')),
                ('eye_side', models.CharField(default='RIGHT', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ai_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='retinal_analysis.aianalysis')),
            ],
            options={
                'verbose_name': 'Retinal Finding',
                'verbose_name_plural': 'Retinal Findings',
            },
        ),
    ]
