# Generated by Django 6.1 on 2026-08-28 07:23

import apps.screenings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_camps', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screening_code', models.CharField(db_index=True, help_text='Unique screening session ID e.g. SCR-1042-04', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Screening Created'), ('IMAGE_PENDING', 'Waiting for Image Capture'), ('ANALYZING', 'AI Inference in Progress'), ('ANALYZED', 'AI Analysis Completed'), ('REVIEW_REQUIRED', 'Ophthalmologist Review Required'), ('REFERRED', 'Referred to Specialist'), ('COMPLETED', 'Screening Completed'), ('FAILED', 'Processing Failed')], db_index=True, default='CREATED', max_length=30)),
                ('screening_date', models.DateField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='patients.patient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_screenings', to=settings.AUTH_USER_MODEL)),
                ('screening_camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='health_camps.screeningcamp')),
            ],
            options={
                'verbose_name': 'Screening Session',
                'verbose_name_plural': 'Screening Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetinalImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.screenings.models.retinal_image_upload_path)),
                ('eye_side', models.CharField(choices=[('RIGHT', 'Right Eye (OD - Oculus Dexter)'), ('LEFT', 'Left Eye (OS - Oculus Sinister)')], db_index=True, default='RIGHT', max_length=10)),
                ('capture_device', models.CharField(default='45° Digital Fundus Camera (Non-Mydriatic)', max_length=150)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=50)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 integrity hash', max_length=64, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Image Uploaded'), ('QUALITY_PASSED', 'Optical Quality Check Passed'), ('QUALITY_FAILED', 'Optical Quality Insufficient'), ('PROCESSED', 'Analyzed by AI')], default='UPLOADED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='screenings.screeningsession')),
            ],
            options={
                'verbose_name': 'Retinal Image',
                'verbose_name_plural': 'Retinal Images',
                'ordering': ['-captured_at'],
            },
        ),
    ]
