# Generated by Django 6.1 on 2026-08-28 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_camps', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0002_patient_patients_pa_organiz_fb112c_idx_and_more'),
        ('screenings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['organization', 'status'], name='screenings__organiz_c98068_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['organization', 'screening_date'], name='screenings__organiz_14df29_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['patient', 'screening_date'], name='screenings__patient_7a71eb_idx'),
        ),
    ]
