# Generated by Django 6.1 on 2026-08-28 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STABLE', 'Stable Retinal Vasculature'), ('IMPROVING', 'Regression / Improving'), ('POSSIBLE_PROGRESSION', 'Possible Longitudinal Progression'), ('SIGNIFICANT_CHANGE', 'Significant Microvascular Change'), ('INSUFFICIENT_DATA', 'Insufficient Prior Data for Longitudinal Comparison')], db_index=True, default='STABLE', max_length=30)),
                ('changes', models.JSONField(blank=True, default=list, help_text='Quantitative list of lesion delta metrics')),
                ('confidence', models.DecimalField(decimal_places=4, default=0.942, max_digits=5)),
                ('velocity_assessment', models.CharField(choices=[('NORMAL', 'Normal / Expected'), ('MODERATE', 'Moderate'), ('HIGH', 'High Velocity / Rapid Progression')], default='HIGH', max_length=20)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_current_progression_evaluations', to='screenings.screeningsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_assessments', to='patients.patient')),
                ('previous_screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_previous_progression_evaluations', to='screenings.screeningsession')),
            ],
            options={
                'verbose_name': 'Progression Assessment',
                'verbose_name_plural': 'Progression Assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SCREENED', 'Retinal Photography Captured'), ('AI_ANALYZED', 'AI Screening Inference Generated'), ('REFERRED', 'Specialist Referral Dispatched'), ('FOLLOWUP_DUE', 'Follow-up Recall Due'), ('FOLLOWUP_COMPLETED', 'Patient Follow-up Completed'), ('SPECIALIST_REVIEWED', 'Vitreoretinal Specialist Examination')], db_index=True, default='SCREENED', max_length=30)),
                ('event_date', models.DateField(db_index=True)),
                ('stage_title', models.CharField(blank=True, max_length=150, null=True)),
                ('severity', models.CharField(default='NO_DR', max_length=30)),
                ('risk_level', models.CharField(default='LOW', max_length=20)),
                ('risk_score', models.PositiveIntegerField(default=10)),
                ('summary', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='patients.patient')),
                ('screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='screenings.screeningsession')),
            ],
            options={
                'verbose_name': 'Screening Timeline Event',
                'verbose_name_plural': 'Screening Timeline Events',
                'ordering': ['event_date', 'created_at'],
            },
        ),
    ]
