# Generated by Django 6.1 on 2026-08-28 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique client-generated idempotency key to prevent duplicate creation.', max_length=100, unique=True)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('entity_type', models.CharField(choices=[('PATIENT', 'Patient Record'), ('SCREENING', 'Screening Session'), ('IMAGE', 'Retinal Image Capture'), ('REFERRAL', 'Specialist Referral'), ('FOLLOWUP', 'Patient Follow-up')], db_index=True, max_length=30)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('operation', models.CharField(choices=[('CREATE', 'Create New Entity'), ('UPDATE', 'Update Existing Entity')], default='CREATE', max_length=20)),
                ('client_timestamp', models.DateTimeField(help_text='Timestamp when record was captured offline on mobile device')),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending Synchronization'), ('SYNCED', 'Successfully Synchronized'), ('FAILED', 'Synchronization Failed'), ('CONFLICT', 'Version Conflict Detected')], db_index=True, default='SYNCED', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Raw payload submitted by offline client')),
                ('server_response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Record',
                'verbose_name_plural': 'Sync Records',
                'ordering': ['-server_timestamp'],
            },
        ),
    ]
