# Generated by Django 6.1 on 2026-08-28 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('synchronization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['device_id', 'sync_status'], name='synchroniza_device__c95ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['organization', 'sync_status'], name='synchroniza_organiz_b1350d_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrecord',
            index=models.Index(fields=['entity_type', 'entity_id'], name='synchroniza_entity__3a9b7c_idx'),
        ),
    ]
