# Generated by Django 6.1 on 2026-08-28 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(db_index=True, help_text='Unique facility identifier code e.g. VREH-01', max_length=50, unique=True)),
                ('org_type', models.CharField(choices=[('HOSPITAL', 'Tertiary / Secondary Eye Hospital'), ('CLINIC', 'Specialty Ophthalmology Clinic'), ('PHC', 'Primary Health Centre / Community Clinic'), ('NGO', 'Non-Governmental Health Organization'), ('GOVT_PROGRAM', 'National Health Screening Mission'), ('CAMP_ORG', 'Rural Screening Camp Organization')], db_index=True, default='HOSPITAL', max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(default='Andhra Pradesh', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_org', models.CharField(choices=[('ADMIN', 'Facility Administrator'), ('DOCTOR', 'Attending Ophthalmologist'), ('HEALTHCARE_WORKER', 'Field Health Worker / ASHA'), ('SCREENING_OPERATOR', 'Camera Operator')], default='HEALTHCARE_WORKER', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
